<?php

abstract class BaseAdapter implements LanguageAdapter
{
    // Make data available to child classes
    protected string $jsonFile;
    protected array $allEnums;
    protected array $uniqueStructs;
    protected array $groupedStructs;
    protected array $allStructs;

    public function generate(
        string $jsonFile,
        array $allEnums,
        array $uniqueStructs,
        array $groupedStructs,
        array $allStructs,
    ): void {
        // Store data
        $this->jsonFile = $jsonFile;
        $this->allEnums = $allEnums;
        $this->uniqueStructs = $uniqueStructs;
        $this->groupedStructs = $groupedStructs;
        $this->allStructs = $allStructs;

        // Call the abstract method that child classes MUST implement
        $this->doGeneration();
    }

    /**
     * The main generation logic for the specific language.
     */
    abstract protected function doGeneration(): void;

    /**
     * Converts SNAKE_CASE to camelCase.
     */
    protected function snakeToCamel(string $snake_case): string
    {
        $parts = explode("_", strtolower($snake_case));
        $camelCase = array_shift($parts);
        foreach ($parts as $part) {
            $camelCase .= ucfirst($part);
        }
        return $camelCase;
    }

    /**
     * Generates the auto-generation warning header for a file.
     */
    protected function getFileHeader(string $generatorName): string
    {
        $jsonBasename = basename($this->jsonFile);
        return "// !!! THIS FILE IS AUTO-GENERATED BY {$generatorName}, DO NOT EDIT !!!\n" .
            "// Generated from: {$jsonBasename}\n\n";
    }
}
