<?php

// !!! THIS FILE IS AUTO-GENERATED BY PhpAdapter.php, DO NOT EDIT !!!
// Generated from: structs.json

namespace Phrost;

// --- Events Enum ---
enum Events: int
{
    case SPRITE_ADD = 0;
    case SPRITE_REMOVE = 1;
    case SPRITE_MOVE = 2;
    case SPRITE_SCALE = 3;
    case SPRITE_RESIZE = 4;
    case SPRITE_ROTATE = 5;
    case SPRITE_COLOR = 6;
    case SPRITE_SPEED = 7;
    case SPRITE_TEXTURE_LOAD = 8;
    case SPRITE_TEXTURE_SET = 9;
    case SPRITE_SET_SOURCE_RECT = 10;
    case GEOM_ADD_POINT = 50;
    case GEOM_ADD_LINE = 51;
    case GEOM_ADD_RECT = 52;
    case GEOM_ADD_FILL_RECT = 53;
    case GEOM_ADD_PACKED = 54;
    case GEOM_REMOVE = 55;
    case GEOM_SET_COLOR = 56;

    case INPUT_KEYUP = 100;
    case INPUT_KEYDOWN = 101;
    case INPUT_MOUSEUP = 102;
    case INPUT_MOUSEDOWN = 103;
    case INPUT_MOUSEMOTION = 104;

    case WINDOW_TITLE = 200;
    case WINDOW_RESIZE = 201;
    case WINDOW_FLAGS = 202;

    case TEXT_ADD = 300;
    case TEXT_SET_STRING = 301;

    case AUDIO_LOAD = 400;
    case AUDIO_LOADED = 401;
    case AUDIO_PLAY = 402;
    case AUDIO_STOP_ALL = 403;
    case AUDIO_SET_MASTER_VOLUME = 404;
    case AUDIO_PAUSE = 405;
    case AUDIO_STOP = 406;
    case AUDIO_UNLOAD = 407;
    case AUDIO_SET_VOLUME = 408;

    case PHYSICS_ADD_BODY = 500;
    case PHYSICS_REMOVE_BODY = 501;
    case PHYSICS_APPLY_FORCE = 502;
    case PHYSICS_APPLY_IMPULSE = 503;
    case PHYSICS_SET_VELOCITY = 504;
    case PHYSICS_SET_POSITION = 505;
    case PHYSICS_SET_ROTATION = 506;
    case PHYSICS_COLLISION_BEGIN = 550;
    case PHYSICS_COLLISION_SEPARATE = 551;
    case PHYSICS_SYNC_TRANSFORM = 552;
    case PHYSICS_SET_DEBUG_MODE = 553;

    case PLUGIN = 1000;
    case PLUGIN_LOAD = 1001;
    case PLUGIN_UNLOAD = 1002;
    case PLUGIN_SET = 1003;
    case PLUGIN_EVENT_STACKING = 1004;
    case PLUGIN_SUBSCRIBE_EVENT = 1005;
    case PLUGIN_UNSUBSCRIBE_EVENT = 1006;

    case CAMERA_SET_POSITION = 2000;
    case CAMERA_MOVE = 2001;
    case CAMERA_SET_ZOOM = 2002;
    case CAMERA_SET_ROTATION = 2003;
    case CAMERA_FOLLOW_ENTITY = 2004;
    case CAMERA_STOP_FOLLOWING = 2005;

    case SCRIPT_SUBSCRIBE = 3000;
    case SCRIPT_UNSUBSCRIBE = 3001;

    case UI_BEGIN_WINDOW = 4000;
    case UI_END_WINDOW = 4001;
    case UI_TEXT = 4002;
    case UI_BUTTON = 4003;
    case UI_ELEMENT_CLICKED = 4500;
}
// --- End Events Enum ---

// --- Pack Format Classes ---
class SpritePackFormats
{
    /**
     * Maps to Swift: `PackedSpriteAddEvent`
     * - id1: i64 (Primary identifier (e.g., entity ID).)
     * - id2: i64 (Secondary identifier (e.g., component ID).)
     * - positionX: f64 (Initial X position.)
     * - positionY: f64 (Initial Y position.)
     * - positionZ: f64 (Initial Z position (depth).)
     * - scaleX: f64 (Initial X scale.)
     * - scaleY: f64 (Initial Y scale.)
     * - scaleZ: f64 (Initial Z scale.)
     * - sizeW: f64 (Initial width.)
     * - sizeH: f64 (Initial height.)
     * - rotationX: f64 (Initial X rotation (in radians).)
     * - rotationY: f64 (Initial Y rotation (in radians).)
     * - rotationZ: f64 (Initial Z rotation (in radians).)
     * - r: u8 (Red color component (0-255).)
     * - g: u8 (Green color component (0-255).)
     * - b: u8 (Blue color component (0-255).)
     * - a: u8 (Alpha color component (0-255).)
     * - _padding: u32 (Ensures 8-byte alignment for speeds.)
     * - speedX: f64 (Initial X speed.)
     * - speedY: f64 (Initial Y speed.)
     */
    public const PACK_SPRITE_ADD = "qid1/qid2/epositionX/epositionY/epositionZ/escaleX/escaleY/escaleZ/esizeW/esizeH/erotationX/erotationY/erotationZ/Cr/Cg/Cb/Ca/x4_padding/espeedX/espeedY";

    /**
     * Maps to Swift: `PackedSpriteRemoveEvent`
     * - id1: i64 (Primary ID of sprite to remove.)
     * - id2: i64 (Secondary ID of sprite to remove.)
     */
    public const PACK_SPRITE_REMOVE = "qid1/qid2";

    /**
     * Maps to Swift: `PackedSpriteMoveEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - positionX: f64 (New X position.)
     * - positionY: f64 (New Y position.)
     * - positionZ: f64 (New Z position (depth).)
     */
    public const PACK_SPRITE_MOVE = "qid1/qid2/epositionX/epositionY/epositionZ";

    /**
     * Maps to Swift: `PackedSpriteScaleEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - scaleX: f64 (New X scale.)
     * - scaleY: f64 (New Y scale.)
     * - scaleZ: f64 (New Z scale.)
     */
    public const PACK_SPRITE_SCALE = "qid1/qid2/escaleX/escaleY/escaleZ";

    /**
     * Maps to Swift: `PackedSpriteResizeEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - sizeW: f64 (New width.)
     * - sizeH: f64 (New height.)
     */
    public const PACK_SPRITE_RESIZE = "qid1/qid2/esizeW/esizeH";

    /**
     * Maps to Swift: `PackedSpriteRotateEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - rotationX: f64 (New X rotation (in radians).)
     * - rotationY: f64 (New Y rotation (in radians).)
     * - rotationZ: f64 (New Z rotation (in radians).)
     */
    public const PACK_SPRITE_ROTATE = "qid1/qid2/erotationX/erotationY/erotationZ";

    /**
     * Maps to Swift: `PackedSpriteColorEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - r: u8 (New red component (0-255).)
     * - g: u8 (New green component (0-255).)
     * - b: u8 (New blue component (0-255).)
     * - a: u8 (New alpha component (0-255).)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_SPRITE_COLOR = "qid1/qid2/Cr/Cg/Cb/Ca/x4_padding";

    /**
     * Maps to Swift: `PackedSpriteSpeedEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - speedX: f64 (New X speed.)
     * - speedY: f64 (New Y speed.)
     */
    public const PACK_SPRITE_SPEED = "qid1/qid2/espeedX/espeedY";

    /**
     * Maps to Swift: `PackedTextureLoadHeaderEvent`
     * (Header struct)
     * - id1: i64 (ID of the sprite this texture is for.)
     * - id2: i64 (Secondary ID.)
     * - filenameLength: u32 (Length of the texture filename that follows this header.)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_SPRITE_TEXTURE_LOAD = "qid1/qid2/VfilenameLength/x4_padding/a*filename";

    /**
     * Maps to Swift: `PackedSpriteTextureSetEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - textureId: u64 (The ID of the loaded texture to set.)
     */
    public const PACK_SPRITE_TEXTURE_SET = "qid1/qid2/QtextureId";

    /**
     * Maps to Swift: `PackedSpriteSetSourceRectEvent`
     * - id1: i64 (Primary ID of the sprite.)
     * - id2: i64 (Secondary ID of the sprite.)
     * - x: f32 (Source rect X coordinate.)
     * - y: f32 (Source rect Y coordinate.)
     * - w: f32 (Source rect Width.)
     * - h: f32 (Source rect Height.)
     */
    public const PACK_SPRITE_SET_SOURCE_RECT = "qid1/qid2/gx/gy/gw/gh";

    /**
     * Maps to Swift: `PackedGeomAddPointEvent`
     * - id1: i64 (Primary identifier.)
     * - id2: i64 (Secondary identifier.)
     * - z: f64 (Z position (depth).)
     * - r: u8 (Red color component (0-255).)
     * - g: u8 (Green color component (0-255).)
     * - b: u8 (Blue color component (0-255).)
     * - a: u8 (Alpha color component (0-255).)
     * - isScreenSpace: u8 (If the geometry is unaffected by the camera.)
     * - _padding: u8 (Padding for alignment.)
     * - x: f32 (X coordinate.)
     * - y: f32 (Y coordinate.)
     */
    public const PACK_GEOM_ADD_POINT = "qid1/qid2/ez/Cr/Cg/Cb/Ca/CisScreenSpace/x3_padding/gx/gy";

    /**
     * Maps to Swift: `PackedGeomAddLineEvent`
     * - id1: i64 (Primary identifier.)
     * - id2: i64 (Secondary identifier.)
     * - z: f64 (Z position (depth).)
     * - r: u8 (Red color component (0-255).)
     * - g: u8 (Green color component (0-255).)
     * - b: u8 (Blue color component (0-255).)
     * - a: u8 (Alpha color component (0-255).)
     * - isScreenSpace: u8 (If the geometry is unaffected by the camera.)
     * - _padding: u8 (Padding for alignment.)
     * - x1: f32 (Start X coordinate.)
     * - y1: f32 (Start Y coordinate.)
     * - x2: f32 (End X coordinate.)
     * - y2: f32 (End Y coordinate.)
     */
    public const PACK_GEOM_ADD_LINE = "qid1/qid2/ez/Cr/Cg/Cb/Ca/CisScreenSpace/x3_padding/gx1/gy1/gx2/gy2";

    /**
     * Maps to Swift: `PackedGeomAddRectEvent`
     * - id1: i64 (Primary identifier.)
     * - id2: i64 (Secondary identifier.)
     * - z: f64 (Z position (depth).)
     * - r: u8 (Red color component (0-255).)
     * - g: u8 (Green color component (0-255).)
     * - b: u8 (Blue color component (0-255).)
     * - a: u8 (Alpha color component (0-255).)
     * - isScreenSpace: u8 (If the geometry is unaffected by the camera.)
     * - _padding: u8 (Padding for alignment.)
     * - x: f32 (Top-left X coordinate.)
     * - y: f32 (Top-left Y coordinate.)
     * - w: f32 (Width.)
     * - h: f32 (Height.)
     */
    public const PACK_GEOM_ADD_RECT = "qid1/qid2/ez/Cr/Cg/Cb/Ca/CisScreenSpace/x3_padding/gx/gy/gw/gh";

    /**
     * Maps to Swift: `PackedGeomAddRectEvent`
     * - id1: i64 (Primary identifier.)
     * - id2: i64 (Secondary identifier.)
     * - z: f64 (Z position (depth).)
     * - r: u8 (Red color component (0-255).)
     * - g: u8 (Green color component (0-255).)
     * - b: u8 (Blue color component (0-255).)
     * - a: u8 (Alpha color component (0-255).)
     * - isScreenSpace: u8 (If the geometry is unaffected by the camera.)
     * - _padding: u8 (Padding for alignment.)
     * - x: f32 (Top-left X coordinate.)
     * - y: f32 (Top-left Y coordinate.)
     * - w: f32 (Width.)
     * - h: f32 (Height.)
     */
    public const PACK_GEOM_ADD_FILL_RECT = "qid1/qid2/ez/Cr/Cg/Cb/Ca/CisScreenSpace/x3_padding/gx/gy/gw/gh";

    /**
     * Maps to Swift: `PackedGeomAddPackedHeaderEvent`
     * (Header struct)
     * - id1: i64 (Primary identifier.)
     * - id2: i64 (Secondary identifier.)
     * - z: f64 (Z position (depth).)
     * - r: u8 (Red color component (0-255).)
     * - g: u8 (Green color component (0-255).)
     * - b: u8 (Blue color component (0-255).)
     * - a: u8 (Alpha color component (0-255).)
     * - isScreenSpace: u8 (If the geometry is unaffected by the camera.)
     * - _padding: u16 (Padding for alignment.)
     * - primitiveType: u32 (Raw value from PrimitiveType enum (point, line, rect).)
     * - count: u32 (Number of primitives that follow this header.)
     */
    public const PACK_GEOM_ADD_PACKED = "qid1/qid2/ez/Cr/Cg/Cb/Ca/CisScreenSpace/x2_padding/VprimitiveType/Vcount";

    /**
     * Maps to Swift: `PackedGeomRemoveEvent`
     * - id1: i64 (Primary ID of geometry to remove.)
     * - id2: i64 (Secondary ID of geometry to remove.)
     */
    public const PACK_GEOM_REMOVE = "qid1/qid2";

    /**
     * Maps to Swift: `PackedGeomSetColorEvent`
     * - id1: i64 (Primary ID of the geometry entity.)
     * - id2: i64 (Secondary ID of the geometry entity.)
     * - r: u8 (New red component (0-255).)
     * - g: u8 (New green component (0-255).)
     * - b: u8 (New blue component (0-255).)
     * - a: u8 (New alpha component (0-255).)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_GEOM_SET_COLOR = "qid1/qid2/Cr/Cg/Cb/Ca/x4_padding";
}

class InputPackFormats
{
    /**
     * Maps to Swift: `PackedKeyEvent`
     * - scancode: i32 (Physical key scancode.)
     * - keycode: u32 (Keycode (e.g., Keycode.A).)
     * - mod: u16 (Key modifiers (Shift, Ctrl, etc.).)
     * - isRepeat: u8 (1 if this is a key repeat, 0 otherwise.)
     * - _padding: u8 (Padding for alignment.)
     */
    public const PACK_INPUT_KEYUP = "lscancode/Vkeycode/Smod/CisRepeat/x_padding";

    /**
     * Maps to Swift: `PackedKeyEvent`
     * - scancode: i32 (Physical key scancode.)
     * - keycode: u32 (Keycode (e.g., Keycode.A).)
     * - mod: u16 (Key modifiers (Shift, Ctrl, etc.).)
     * - isRepeat: u8 (1 if this is a key repeat, 0 otherwise.)
     * - _padding: u8 (Padding for alignment.)
     */
    public const PACK_INPUT_KEYDOWN = "lscancode/Vkeycode/Smod/CisRepeat/x_padding";

    /**
     * Maps to Swift: `PackedMouseButtonEvent`
     * - x: f32 (X coordinate of the mouse.)
     * - y: f32 (Y coordinate of the mouse.)
     * - button: u8 (Mouse button index.)
     * - clicks: u8 (Number of clicks (1 for single, 2 for double).)
     * - _padding: u16 (Padding for alignment.)
     */
    public const PACK_INPUT_MOUSEUP = "gx/gy/Cbutton/Cclicks/x2_padding";

    /**
     * Maps to Swift: `PackedMouseButtonEvent`
     * - x: f32 (X coordinate of the mouse.)
     * - y: f32 (Y coordinate of the mouse.)
     * - button: u8 (Mouse button index.)
     * - clicks: u8 (Number of clicks (1 for single, 2 for double).)
     * - _padding: u16 (Padding for alignment.)
     */
    public const PACK_INPUT_MOUSEDOWN = "gx/gy/Cbutton/Cclicks/x2_padding";

    /**
     * Maps to Swift: `PackedMouseMotionEvent`
     * - x: f32 (Absolute X coordinate.)
     * - y: f32 (Absolute Y coordinate.)
     * - xrel: f32 (Relative X motion.)
     * - yrel: f32 (Relative Y motion.)
     */
    public const PACK_INPUT_MOUSEMOTION = "gx/gy/gxrel/gyrel";
}

class WindowPackFormats
{
    /**
     * Maps to Swift: `PackedWindowTitleEvent`
     * - title: char[256] (A fixed-size 256-byte NUL-padded string for the title.)
     */
    public const PACK_WINDOW_TITLE = "a256title";

    /**
     * Maps to Swift: `PackedWindowResizeEvent`
     * - w: i32 (New window width.)
     * - h: i32 (New window height.)
     */
    public const PACK_WINDOW_RESIZE = "lw/lh";

    /**
     * Maps to Swift: `PackedWindowFlagsEvent`
     * - flags: u64 (Bitmask of window flags.)
     */
    public const PACK_WINDOW_FLAGS = "Qflags";
}

class TextPackFormats
{
    /**
     * Maps to Swift: `PackedTextAddEvent`
     * (Header struct)
     * - id1: i64 (Primary identifier.)
     * - id2: i64 (Secondary identifier.)
     * - positionX: f64 (Initial X position.)
     * - positionY: f64 (Initial Y position.)
     * - positionZ: f64 (Initial Z position (depth).)
     * - r: u8 (Red color component (0-255).)
     * - g: u8 (Green color component (0-255).)
     * - b: u8 (Blue color component (0-255).)
     * - a: u8 (Alpha color component (0-255).)
     * - _padding1: u32 (Padding for alignment.)
     * - fontSize: f32 (Font size.)
     * - fontPathLength: u32 (Length of the font path string that follows.)
     * - textLength: u32 (Length of the initial text string that follows.)
     * - _padding2: u32 (Padding.)
     */
    public const PACK_TEXT_ADD = "qid1/qid2/epositionX/epositionY/epositionZ/Cr/Cg/Cb/Ca/x4_padding1/gfontSize/VfontPathLength/VtextLength/x4_padding2/a*fontPath/a*text";

    /**
     * Maps to Swift: `PackedTextSetStringEvent`
     * (Header struct)
     * - id1: i64 (Primary ID of the text entity.)
     * - id2: i64 (Secondary ID of the text entity.)
     * - textLength: u32 (Length of the new text string that follows this header.)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_TEXT_SET_STRING = "qid1/qid2/VtextLength/x4_padding/a*text";
}

class AudioPackFormats
{
    /**
     * Maps to Swift: `PackedAudioLoadEvent`
     * (Header struct)
     * - pathLength: u32 (Length of the audio file path that follows.)
     */
    public const PACK_AUDIO_LOAD = "VpathLength/a*path";

    /**
     * Maps to Swift: `PackedAudioLoadedEvent`
     * - audioId: u64 (The ID assigned to the loaded audio.)
     */
    public const PACK_AUDIO_LOADED = "QaudioId";

    /**
     * Maps to Swift: `PackedAudioPlayEvent`
     * - audioId: u64 (The ID of the audio to play.)
     */
    public const PACK_AUDIO_PLAY = "QaudioId";

    /**
     * Maps to Swift: `PackedAudioStopAllEvent`
     * - _unused: u8 (Padding to ensure non-zero struct size (MSVC compatibility).)
     */
    public const PACK_AUDIO_STOP_ALL = "C_unused";

    /**
     * Maps to Swift: `PackedAudioSetMasterVolumeEvent`
     * - volume: f32 (Volume level (e.g., 0.0 to 1.0).)
     */
    public const PACK_AUDIO_SET_MASTER_VOLUME = "gvolume";

    /**
     * Maps to Swift: `PackedAudioPauseEvent`
     * - audioId: u64 (The ID of the audio to pause.)
     */
    public const PACK_AUDIO_PAUSE = "QaudioId";

    /**
     * Maps to Swift: `PackedAudioStopEvent`
     * - audioId: u64 (The ID of the audio to stop.)
     */
    public const PACK_AUDIO_STOP = "QaudioId";

    /**
     * Maps to Swift: `PackedAudioUnloadEvent`
     * - audioId: u64 (The ID of the audio to unload.)
     */
    public const PACK_AUDIO_UNLOAD = "QaudioId";

    /**
     * Maps to Swift: `PackedAudioSetVolumeEvent`
     * - audioId: u64 (The ID of the audio to modify.)
     * - volume: f32 (Volume level (0.0 to 1.0).)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_AUDIO_SET_VOLUME = "QaudioId/gvolume/x4_padding";
}

class PhysicsPackFormats
{
    /**
     * Maps to Swift: `PackedPhysicsAddBodyEvent`
     * - id1: i64 (Primary identifier.)
     * - id2: i64 (Secondary identifier.)
     * - positionX: f64 (Initial X position.)
     * - positionY: f64 (Initial Y position.)
     * - bodyType: u8 (Body type (static, kinematic, dynamic).)
     * - shapeType: u8 (Shape type (box, circle).)
     * - lockRotation: u8 (Rotation lock (0 = unlocked, 1 = locked). Prevent bodies from falling over.)
     * - _padding: u8 (Padding for 8-byte alignment.)
     * - mass: f64 (Mass of the body.)
     * - friction: f64 (Friction coefficient.)
     * - elasticity: f64 (Elasticity (bounciness).)
     * - width: f64 (Width of the shape (or radius).)
     * - height: f64 (Height of the shape (unused if circle).)
     */
    public const PACK_PHYSICS_ADD_BODY = "qid1/qid2/epositionX/epositionY/CbodyType/CshapeType/ClockRotation/x5_padding/emass/efriction/eelasticity/ewidth/eheight";

    /**
     * Maps to Swift: `PackedPhysicsRemoveBodyEvent`
     * - id1: i64 (Primary ID of body to remove.)
     * - id2: i64 (Secondary ID of body to remove.)
     */
    public const PACK_PHYSICS_REMOVE_BODY = "qid1/qid2";

    /**
     * Maps to Swift: `PackedPhysicsApplyForceEvent`
     * - id1: i64 (Primary ID of the body.)
     * - id2: i64 (Secondary ID of the body.)
     * - forceX: f64 (Force vector X component.)
     * - forceY: f64 (Force vector Y component.)
     */
    public const PACK_PHYSICS_APPLY_FORCE = "qid1/qid2/eforceX/eforceY";

    /**
     * Maps to Swift: `PackedPhysicsApplyImpulseEvent`
     * - id1: i64 (Primary ID of the body.)
     * - id2: i64 (Secondary ID of the body.)
     * - impulseX: f64 (Impulse vector X component.)
     * - impulseY: f64 (Impulse vector Y component.)
     */
    public const PACK_PHYSICS_APPLY_IMPULSE = "qid1/qid2/eimpulseX/eimpulseY";

    /**
     * Maps to Swift: `PackedPhysicsSetVelocityEvent`
     * - id1: i64 (Primary ID of the body.)
     * - id2: i64 (Secondary ID of the body.)
     * - velocityX: f64 (New X velocity.)
     * - velocityY: f64 (New Y velocity.)
     */
    public const PACK_PHYSICS_SET_VELOCITY = "qid1/qid2/evelocityX/evelocityY";

    /**
     * Maps to Swift: `PackedPhysicsSetPositionEvent`
     * - id1: i64 (Primary ID of the body.)
     * - id2: i64 (Secondary ID of the body.)
     * - positionX: f64 (New X position.)
     * - positionY: f64 (New Y position.)
     */
    public const PACK_PHYSICS_SET_POSITION = "qid1/qid2/epositionX/epositionY";

    /**
     * Maps to Swift: `PackedPhysicsSetRotationEvent`
     * - id1: i64 (Primary ID of the body.)
     * - id2: i64 (Secondary ID of the body.)
     * - angleInRadians: f64 (New angle in radians.)
     */
    public const PACK_PHYSICS_SET_ROTATION = "qid1/qid2/eangleInRadians";

    /**
     * Maps to Swift: `PackedPhysicsCollisionEvent`
     * - id1_A: i64 (Primary ID of the first body.)
     * - id2_A: i64 (Secondary ID of the first body.)
     * - id1_B: i64 (Primary ID of the second body.)
     * - id2_B: i64 (Secondary ID of the second body.)
     */
    public const UNPACK_PHYSICS_COLLISION = "qid1_A/qid2_A/qid1_B/qid2_B";

    /**
     * Maps to Swift: `PackedPhysicsSyncTransformEvent`
     * - id1: i64 (Primary ID of the body.)
     * - id2: i64 (Secondary ID of the body.)
     * - positionX: f64 (Current X position.)
     * - positionY: f64 (Current Y position.)
     * - angle: f64 (Current rotation (in radians).)
     * - velocityX: f64 (Current X velocity.)
     * - velocityY: f64 (Current Y velocity.)
     * - angularVelocity: f64 (Current angular velocity (spin speed) in radians/sec.)
     * - isSleeping: u8 (1 if the body is sleeping, 0 if active.)
     * - _padding: u8 (Aligns struct to 64-bit boundary.)
     */
    public const UNPACK_PHYSICS_SYNC_TRANSFORM = "qid1/qid2/epositionX/epositionY/eangle/evelocityX/evelocityY/eangularVelocity/CisSleeping/x7_padding";

    /**
     * Maps to Swift: `PackedPhysicsSetDebugModeEvent`
     * - enabled: u8 (1 to enable debug drawing, 0 to disable.)
     * - _padding: u8 (Padding for 4-byte alignment.)
     */
    public const PACK_PHYSICS_SET_DEBUG_MODE = "Cenabled/x3_padding";
}

class PluginPackFormats
{
    /**
     * Maps to Swift: `PackedPluginOnEvent`
     * - eventId: u8 (A custom event ID for the plugin.)
     */
    public const PACK_PLUGIN = "CeventId";

    /**
     * Maps to Swift: `PackedPluginLoadHeaderEvent`
     * (Header struct)
     * - channelNo: u32 (Initial Channel number to receive events from. Look at channel subscription event to listen to more than one channel.)
     * - pathLength: u32 (Length of the plugin file path that follows.)
     */
    public const PACK_PLUGIN_LOAD = "VchannelNo/VpathLength/a*path";

    /**
     * Maps to Swift: `PackedPluginUnloadEvent`
     * - pluginId: u8 (ID of the plugin to unload.)
     */
    public const PACK_PLUGIN_UNLOAD = "CpluginId";

    /**
     * Maps to Swift: `PackedPluginSetEvent`
     * - pluginId: u8 (ID of the plugin to set as active.)
     */
    public const PACK_PLUGIN_SET = "CpluginId";

    /**
     * Maps to Swift: `PackedPluginEventStackingEvent`
     * - eventId: u8 (1 to enable stacking, 0 to disable.)
     * - _padding: u8 (Padding for alignment.)
     */
    public const PACK_PLUGIN_EVENT_STACKING = "CeventId/x_padding";

    /**
     * Maps to Swift: `PackedPluginSubscribeEvent`
     * - pluginId: u8 (ID of the plugin.)
     * - _padding: u8 (Padding for alignment.)
     * - channelNo: u32 (Channel number to receive events from.)
     */
    public const PACK_PLUGIN_SUBSCRIBE_EVENT = "CpluginId/x3_padding/VchannelNo";

    /**
     * Maps to Swift: `PackedPluginUnsubscribeEvent`
     * - pluginId: u8 (ID of the plugin.)
     * - _padding: u8 (Padding for alignment.)
     * - channelNo: u32 (Channel number to stop receiving events from.)
     */
    public const PACK_PLUGIN_UNSUBSCRIBE_EVENT = "CpluginId/x3_padding/VchannelNo";
}

class CameraPackFormats
{
    /**
     * Maps to Swift: `PackedCameraSetPositionEvent`
     * - positionX: f64 (New X position for the camera's top-left corner.)
     * - positionY: f64 (New Y position for the camera's top-left corner.)
     */
    public const PACK_CAMERA_SET_POSITION = "epositionX/epositionY";

    /**
     * Maps to Swift: `PackedCameraMoveEvent`
     * - deltaX: f64 (Amount to move the camera on the X axis.)
     * - deltaY: f64 (Amount to move the camera on the Y axis.)
     */
    public const PACK_CAMERA_MOVE = "edeltaX/edeltaY";

    /**
     * Maps to Swift: `PackedCameraSetZoomEvent`
     * - zoom: f64 (New zoom level. 1.0 is default, 2.0 is zoomed in.)
     */
    public const PACK_CAMERA_SET_ZOOM = "ezoom";

    /**
     * Maps to Swift: `PackedCameraSetRotationEvent`
     * - angleInRadians: f64 (New camera rotation in radians.)
     */
    public const PACK_CAMERA_SET_ROTATION = "eangleInRadians";

    /**
     * Maps to Swift: `PackedCameraFollowEntityEvent`
     * - id1: i64 (Primary ID of the entity to follow.)
     * - id2: i64 (Secondary ID of the entity to follow.)
     */
    public const PACK_CAMERA_FOLLOW_ENTITY = "qid1/qid2";

    /**
     * Maps to Swift: `PackedCameraStopFollowingEvent`
     * - _unused: u8 (Padding to ensure non-zero struct size (MSVC compatibility).)
     */
    public const PACK_CAMERA_STOP_FOLLOWING = "C_unused";
}

class ScriptPackFormats
{
    /**
     * Maps to Swift: `PackedScriptSubscribeEvent`
     * - channelNo: u32 (Channel number to start receiving events from.)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_SCRIPT_SUBSCRIBE = "VchannelNo/x4_padding";

    /**
     * Maps to Swift: `PackedScriptUnsubscribeEvent`
     * - channelNo: u32 (Channel number to stop receiving events from.)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_SCRIPT_UNSUBSCRIBE = "VchannelNo/x4_padding";
}

class UiPackFormats
{
    /**
     * Maps to Swift: `PackedUIBeginWindowHeaderEvent`
     * (Header struct)
     * - x: f32 (Window X position (set to -1 for default/auto).)
     * - y: f32 (Window Y position (set to -1 for default/auto).)
     * - w: f32 (Window width (0 for auto).)
     * - h: f32 (Window height (0 for auto).)
     * - flags: u32 (ImGui Window flags (e.g., NoResize, NoMove).)
     * - titleLength: u32 (Length of the window title string that follows.)
     */
    public const PACK_UI_BEGIN_WINDOW = "gx/gy/gw/gh/Vflags/VtitleLength";

    /**
     * Maps to Swift: `PackedUIEndWindowEvent`
     * - _unused: u8 (Padding to ensure non-zero struct size.)
     */
    public const PACK_UI_END_WINDOW = "C_unused";

    /**
     * Maps to Swift: `PackedUITextHeaderEvent`
     * (Header struct)
     * - textLength: u32 (Length of the text string that follows.)
     * - _padding: u32 (Padding for alignment.)
     */
    public const PACK_UI_TEXT = "VtextLength/x4_padding";

    /**
     * Maps to Swift: `PackedUIButtonHeaderEvent`
     * (Header struct)
     * - id: u32 (Unique ID for this button to track clicks.)
     * - w: f32 (Button width (0 for auto).)
     * - h: f32 (Button height (0 for auto).)
     * - labelLength: u32 (Length of the label string that follows.)
     */
    public const PACK_UI_BUTTON = "Vid/gw/gh/VlabelLength";

    /**
     * Maps to Swift: `PackedUIInteractionEvent`
     * - elementId: u32 (The ID of the element that was clicked.)
     * - interactionType: u32 (Type of interaction (0 = Click, etc).)
     */
    public const PACK_UI_ELEMENT_CLICKED = "VelementId/VinteractionType";
}
// --- End Pack Format Classes ---
