from enum import IntEnum


# --- Events Enum ---
class Events(enum.IntEnum):
    SPRITE_ADD = 0
    SPRITE_REMOVE = 1
    SPRITE_MOVE = 2
    SPRITE_SCALE = 3
    SPRITE_RESIZE = 4
    SPRITE_ROTATE = 5
    SPRITE_COLOR = 6
    SPRITE_SPEED = 7
    SPRITE_TEXTURE_LOAD = 8
    SPRITE_TEXTURE_SET = 9
    SPRITE_SET_SOURCE_RECT = 10
    GEOM_ADD_POINT = 50
    GEOM_ADD_LINE = 51
    GEOM_ADD_RECT = 52
    GEOM_ADD_FILL_RECT = 53
    GEOM_ADD_PACKED = 54
    GEOM_REMOVE = 55
    GEOM_SET_COLOR = 56

    INPUT_KEYUP = 100
    INPUT_KEYDOWN = 101
    INPUT_MOUSEUP = 102
    INPUT_MOUSEDOWN = 103
    INPUT_MOUSEMOTION = 104

    WINDOW_TITLE = 200
    WINDOW_RESIZE = 201
    WINDOW_FLAGS = 202

    TEXT_ADD = 300
    TEXT_SET_STRING = 301

    AUDIO_LOAD = 400
    AUDIO_LOADED = 401
    AUDIO_PLAY = 402
    AUDIO_STOP_ALL = 403
    AUDIO_SET_MASTER_VOLUME = 404
    AUDIO_PAUSE = 405
    AUDIO_STOP = 406
    AUDIO_UNLOAD = 407
    AUDIO_SET_VOLUME = 408

    PHYSICS_ADD_BODY = 500
    PHYSICS_REMOVE_BODY = 501
    PHYSICS_APPLY_FORCE = 502
    PHYSICS_APPLY_IMPULSE = 503
    PHYSICS_SET_VELOCITY = 504
    PHYSICS_SET_POSITION = 505
    PHYSICS_SET_ROTATION = 506
    PHYSICS_COLLISION_BEGIN = 550
    PHYSICS_COLLISION_SEPARATE = 551
    PHYSICS_SYNC_TRANSFORM = 552

    PLUGIN = 1000
    PLUGIN_LOAD = 1001
    PLUGIN_UNLOAD = 1002
    PLUGIN_SET = 1003
    PLUGIN_EVENT_STACKING = 1004
    PLUGIN_SUBSCRIBE_EVENT = 1005
    PLUGIN_UNSUBSCRIBE_EVENT = 1006

    CAMERA_SET_POSITION = 2000
    CAMERA_MOVE = 2001
    CAMERA_SET_ZOOM = 2002
    CAMERA_SET_ROTATION = 2003
    CAMERA_FOLLOW_ENTITY = 2004
    CAMERA_STOP_FOLLOWING = 2005

    SCRIPT_SUBSCRIBE = 3000
    SCRIPT_UNSUBSCRIBE = 3001


# --- End Events Enum ---
