# Import the Scancode enum from the file created above
from Scancode import Scancode


class Keycode:
    """
    Port of Phrost\Keycode
    This class is not meant to be instantiated.
    """

    def __init__(self):
        # The original class was final with a private constructor.
        # This prevents instantiation in Python.
        raise RuntimeError("Keycode class should not be instantiated")

    SCANCODE_MASK = 1 << 30
    EXTENDED_MASK = 1 << 29

    @staticmethod
    def fromScancode(scancode: Scancode) -> int:
        return scancode.value | Keycode.SCANCODE_MASK

    UNKNOWN = 0
    RETURN = 13
    ESCAPE = 27
    BACKSPACE = 8
    TAB = 9
    SPACE = 32
    EXCLAIM = 33
    DBLAPOSTROPHE = 34
    HASH = 35
    DOLLAR = 36
    PERCENT = 37
    AMPERSAND = 38
    APOSTROPHE = 39
    LEFTPAREN = 40
    RIGHTPAREN = 41
    ASTERISK = 42
    PLUS = 43
    COMMA = 44
    MINUS = 45
    PERIOD = 46
    SLASH = 47
    KEY_0 = 48
    KEY_1 = 49
    KEY_2 = 50
    KEY_3 = 51
    KEY_4 = 52
    KEY_5 = 53
    KEY_6 = 54
    KEY_7 = 55
    KEY_8 = 56
    KEY_9 = 57
    COLON = 58
    SEMICOLON = 59
    LESS = 60
    EQUALS = 61
    GREATER = 62
    QUESTION = 63
    AT = 64
    LEFTBRACKET = 91
    BACKSLASH = 92
    RIGHTBRACKET = 93
    CARET = 94
    UNDERSCORE = 95
    GRAVE = 96
    A = 97
    B = 98
    C = 99
    D = 100
    E = 101
    F = 102
    G = 103
    H = 104
    I = 105
    J = 106
    K = 107
    L = 108
    M = 109
    N = 110
    O = 111
    P = 112
    Q = 113
    R = 114
    S = 115
    T = 116
    U = 117
    V = 118
    W = 119
    X = 120
    Y = 121
    Z = 122
    LEFTBRACE = 123
    PIPE = 124
    RIGHTBRACE = 125
    TILDE = 126
    DELETE = 127
    PLUSMINUS = 177
    CAPSLOCK = SCANCODE_MASK | Scancode.CAPSLOCK.value
    F1 = SCANCODE_MASK | Scancode.F1.value
    F2 = SCANCODE_MASK | Scancode.F2.value
    F3 = SCANCODE_MASK | Scancode.F3.value
    F4 = SCANCODE_MASK | Scancode.F4.value
    F5 = SCANCODE_MASK | Scancode.F5.value
    F6 = SCANCODE_MASK | Scancode.F6.value
    F7 = SCANCODE_MASK | Scancode.F7.value
    F8 = SCANCODE_MASK | Scancode.F8.value
    F9 = SCANCODE_MASK | Scancode.F9.value
    F10 = SCANCODE_MASK | Scancode.F10.value
    F11 = SCANCODE_MASK | Scancode.F11.value
    F12 = SCANCODE_MASK | Scancode.F12.value
    PRINTSCREEN = SCANCODE_MASK | Scancode.PRINTSCREEN.value
    SCROLLLOCK = SCANCODE_MASK | Scancode.SCROLLLOCK.value
    PAUSE = SCANCODE_MASK | Scancode.PAUSE.value
    INSERT = SCANCODE_MASK | Scancode.INSERT.value
    HOME = SCANCODE_MASK | Scancode.HOME.value
    PAGEUP = SCANCODE_MASK | Scancode.PAGEUP.value
    END = SCANCODE_MASK | Scancode.END.value
    PAGEDOWN = SCANCODE_MASK | Scancode.PAGEDOWN.value
    RIGHT = SCANCODE_MASK | Scancode.RIGHT.value
    LEFT = SCANCODE_MASK | Scancode.LEFT.value
    DOWN = SCANCODE_MASK | Scancode.DOWN.value
    UP = SCANCODE_MASK | Scancode.UP.value
    NUMLOCKCLEAR = SCANCODE_MASK | Scancode.NUMLOCKCLEAR.value
    KP_DIVIDE = SCANCODE_MASK | Scancode.KP_DIVIDE.value
    KP_MULTIPLY = SCANCODE_MASK | Scancode.KP_MULTIPLY.value
    KP_MINUS = SCANCODE_MASK | Scancode.KP_MINUS.value
    KP_PLUS = SCANCODE_MASK | Scancode.KP_PLUS.value
    KP_ENTER = SCANCODE_MASK | Scancode.KP_ENTER.value
    KP_1 = SCANCODE_MASK | Scancode.KP_1.value
    KP_2 = SCANCODE_MASK | Scancode.KP_2.value
    KP_3 = SCANCODE_MASK | Scancode.KP_3.value
    KP_4 = SCANCODE_MASK | Scancode.KP_4.value
    KP_5 = SCANCODE_MASK | Scancode.KP_5.value
    KP_6 = SCANCODE_MASK | Scancode.KP_6.value
    KP_7 = SCANCODE_MASK | Scancode.KP_7.value
    KP_8 = SCANCODE_MASK | Scancode.KP_8.value
    KP_9 = SCANCODE_MASK | Scancode.KP_9.value
    KP_0 = SCANCODE_MASK | Scancode.KP_0.value
    KP_PERIOD = SCANCODE_MASK | Scancode.KP_PERIOD.value
    APPLICATION = SCANCODE_MASK | Scancode.APPLICATION.value
    POWER = SCANCODE_MASK | Scancode.POWER.value
    KP_EQUALS = SCANCODE_MASK | Scancode.KP_EQUALS.value
    F13 = SCANCODE_MASK | Scancode.F13.value
    F14 = SCANCODE_MASK | Scancode.F14.value
    F15 = SCANCODE_MASK | Scancode.F15.value
    F16 = SCANCODE_MASK | Scancode.F16.value
    F17 = SCANCODE_MASK | Scancode.F17.value
    F18 = SCANCODE_MASK | Scancode.F18.value
    F19 = SCANCODE_MASK | Scancode.F19.value
    F20 = SCANCODE_MASK | Scancode.F20.value
    F21 = SCANCODE_MASK | Scancode.F21.value
    F22 = SCANCODE_MASK | Scancode.F22.value
    F23 = SCANCODE_MASK | Scancode.F23.value
    F24 = SCANCODE_MASK | Scancode.F24.value
    EXECUTE = SCANCODE_MASK | Scancode.EXECUTE.value
    HELP = SCANCODE_MASK | Scancode.HELP.value
    MENU = SCANCODE_MASK | Scancode.MENU.value
    SELECT = SCANCODE_MASK | Scancode.SELECT.value
    STOP = SCANCODE_MASK | Scancode.STOP.value
    AGAIN = SCANCODE_MASK | Scancode.AGAIN.value
    UNDO = SCANCODE_MASK | Scancode.UNDO.value
    CUT = SCANCODE_MASK | Scancode.CUT.value
    COPY = SCANCODE_MASK | Scancode.COPY.value
    PASTE = SCANCODE_MASK | Scancode.PASTE.value
    FIND = SCANCODE_MASK | Scancode.FIND.value
    MUTE = SCANCODE_MASK | Scancode.MUTE.value
    VOLUMEUP = SCANCODE_MASK | Scancode.VOLUMEUP.value
    VOLUMEDOWN = SCANCODE_MASK | Scancode.VOLUMEDOWN.value
    KP_COMMA = SCANCODE_MASK | Scancode.KP_COMMA.value
    KP_EQUALSAS400 = SCANCODE_MASK | Scancode.KP_EQUALSAS400.value
    ALTERASE = SCANCODE_MASK | Scancode.ALTERASE.value
    SYSREQ = SCANCODE_MASK | Scancode.SYSREQ.value
    CANCEL = SCANCODE_MASK | Scancode.CANCEL.value
    CLEAR = SCANCODE_MASK | Scancode.CLEAR.value
    PRIOR = SCANCODE_MASK | Scancode.PRIOR.value
    RETURN2 = SCANCODE_MASK | Scancode.RETURN2.value
    SEPARATOR = SCANCODE_MASK | Scancode.SEPARATOR.value
    OUT = SCANCODE_MASK | Scancode.OUT.value
    OPER = SCANCODE_MASK | Scancode.OPER.value
    CLEARAGAIN = SCANCODE_MASK | Scancode.CLEARAGAIN.value
    CRSEL = SCANCODE_MASK | Scancode.CRSEL.value
    EXSEL = SCANCODE_MASK | Scancode.EXSEL.value
    KP_00 = SCANCODE_MASK | Scancode.KP_00.value
    KP_000 = SCANCODE_MASK | Scancode.KP_000.value
    THOUSANDSSEPARATOR = SCANCODE_MASK | Scancode.THOUSANDSSEPARATOR.value
    DECIMALSEPARATOR = SCANCODE_MASK | Scancode.DECIMALSEPARATOR.value
    CURRENCYUNIT = SCANCODE_MASK | Scancode.CURRENCYUNIT.value
    CURRENCYSUBUNIT = SCANCODE_MASK | Scancode.CURRENCYSUBUNIT.value
    KP_LEFTPAREN = SCANCODE_MASK | Scancode.KP_LEFTPAREN.value
    KP_RIGHTPAREN = SCANCODE_MASK | Scancode.KP_RIGHTPAREN.value
    KP_LEFTBRACE = SCANCODE_MASK | Scancode.KP_LEFTBRACE.value
    KP_RIGHTBRACE = SCANCODE_MASK | Scancode.KP_RIGHTBRACE.value
    KP_TAB = SCANCODE_MASK | Scancode.KP_TAB.value
    KP_BACKSPACE = SCANCODE_MASK | Scancode.KP_BACKSPACE.value
    KP_A = SCANCODE_MASK | Scancode.KP_A.value
    KP_B = SCANCODE_MASK | Scancode.KP_B.value
    KP_C = SCANCODE_MASK | Scancode.KP_C.value
    KP_D = SCANCODE_MASK | Scancode.KP_D.value
    KP_E = SCANCODE_MASK | Scancode.KP_E.value
    KP_F = SCANCODE_MASK | Scancode.KP_F.value
    KP_XOR = SCANCODE_MASK | Scancode.KP_XOR.value
    KP_POWER = SCANCODE_MASK | Scancode.KP_POWER.value
    KP_PERCENT = SCANCODE_MASK | Scancode.KP_PERCENT.value
    KP_LESS = SCANCODE_MASK | Scancode.KP_LESS.value
    KP_GREATER = SCANCODE_MASK | Scancode.KP_GREATER.value
    KP_AMPERSAND = SCANCODE_MASK | Scancode.KP_AMPERSAND.value
    KP_DBLAMPERSAND = SCANCODE_MASK | Scancode.KP_DBLAMPERSAND.value
    KP_VERTICALBAR = SCANCODE_MASK | Scancode.KP_VERTICALBAR.value
    KP_DBLVERTICALBAR = SCANCODE_MASK | Scancode.KP_DBLVERTICALBAR.value
    KP_COLON = SCANCODE_MASK | Scancode.KP_COLON.value
    KP_HASH = SCANCODE_MASK | Scancode.KP_HASH.value
    KP_SPACE = SCANCODE_MASK | Scancode.KP_SPACE.value
    KP_AT = SCANCODE_MASK | Scancode.KP_AT.value
    KP_EXCLAM = SCANCODE_MASK | Scancode.KP_EXCLAM.value
    KP_MEMSTORE = SCANCODE_MASK | Scancode.KP_MEMSTORE.value
    KP_MEMRECALL = SCANCODE_MASK | Scancode.KP_MEMRECALL.value
    KP_MEMCLEAR = SCANCODE_MASK | Scancode.KP_MEMCLEAR.value
    KP_MEMADD = SCANCODE_MASK | Scancode.KP_MEMADD.value
    KP_MEMSUBTRACT = SCANCODE_MASK | Scancode.KP_MEMSUBTRACT.value
    KP_MEMMULTIPLY = SCANCODE_MASK | Scancode.KP_MEMMULTIPLY.value
    KP_MEMDIVIDE = SCANCODE_MASK | Scancode.KP_MEMDIVIDE.value
    KP_PLUSMINUS = SCANCODE_MASK | Scancode.KP_PLUSMINUS.value
    KP_CLEAR = SCANCODE_MASK | Scancode.KP_CLEAR.value
    KP_CLEARENTRY = SCANCODE_MASK | Scancode.KP_CLEARENTRY.value
    KP_BINARY = SCANCODE_MASK | Scancode.KP_BINARY.value
    KP_OCTAL = SCANCODE_MASK | Scancode.KP_OCTAL.value
    KP_DECIMAL = SCANCODE_MASK | Scancode.KP_DECIMAL.value
    KP_HEXADECIMAL = SCANCODE_MASK | Scancode.KP_HEXADECIMAL.value
    LCTRL = SCANCODE_MASK | Scancode.LCTRL.value
    LSHIFT = SCANCODE_MASK | Scancode.LSHIFT.value
    LALT = SCANCODE_MASK | Scancode.LALT.value
    LGUI = SCANCODE_MASK | Scancode.LGUI.value
    RCTRL = SCANCODE_MASK | Scancode.RCTRL.value
    RSHIFT = SCANCODE_MASK | Scancode.RSHIFT.value
    RALT = SCANCODE_MASK | Scancode.RALT.value
    RGUI = SCANCODE_MASK | Scancode.RGUI.value
    MODE = SCANCODE_MASK | Scancode.MODE.value
    SLEEP = SCANCODE_MASK | Scancode.SLEEP.value
    WAKE = SCANCODE_MASK | Scancode.WAKE.value
    CHANNEL_INCREMENT = SCANCODE_MASK | Scancode.CHANNEL_INCREMENT.value
    CHANNEL_DECREMENT = SCANCODE_MASK | Scancode.CHANNEL_DECREMENT.value
    MEDIA_PLAY = SCANCODE_MASK | Scancode.MEDIA_PLAY.value
    MEDIA_PAUSE = SCANCODE_MASK | Scancode.MEDIA_PAUSE.value
    MEDIA_RECORD = SCANCODE_MASK | Scancode.MEDIA_RECORD.value
    MEDIA_FAST_FORWARD = SCANCODE_MASK | Scancode.MEDIA_FAST_FORWARD.value
    MEDIA_REWIND = SCANCODE_MASK | Scancode.MEDIA_REWIND.value
    MEDIA_NEXT_TRACK = SCANCODE_MASK | Scancode.MEDIA_NEXT_TRACK.value
    MEDIA_PREVIOUS_TRACK = SCANCODE_MASK | Scancode.MEDIA_PREVIOUS_TRACK.value
    MEDIA_STOP = SCANCODE_MASK | Scancode.MEDIA_STOP.value
    MEDIA_EJECT = SCANCODE_MASK | Scancode.MEDIA_EJECT.value
    MEDIA_PLAY_PAUSE = SCANCODE_MASK | Scancode.MEDIA_PLAY_PAUSE.value
    MEDIA_SELECT = SCANCODE_MASK | Scancode.MEDIA_SELECT.value
    AC_NEW = SCANCODE_MASK | Scancode.AC_NEW.value
    AC_OPEN = SCANCODE_MASK | Scancode.AC_OPEN.value
    AC_CLOSE = SCANCODE_MASK | Scancode.AC_CLOSE.value
    AC_EXIT = SCANCODE_MASK | Scancode.AC_EXIT.value
    AC_SAVE = SCANCODE_MASK | Scancode.AC_SAVE.value
    AC_PRINT = SCANCODE_MASK | Scancode.AC_PRINT.value
    AC_PROPERTIES = SCANCODE_MASK | Scancode.AC_PROPERTIES.value
    AC_SEARCH = SCANCODE_MASK | Scancode.AC_SEARCH.value
    AC_HOME = SCANCODE_MASK | Scancode.AC_HOME.value
    AC_BACK = SCANCODE_MASK | Scancode.AC_BACK.value
    AC_FORWARD = SCANCODE_MASK | Scancode.AC_FORWARD.value
    AC_STOP = SCANCODE_MASK | Scancode.AC_STOP.value
    AC_REFRESH = SCANCODE_MASK | Scancode.AC_REFRESH.value
    AC_BOOKMARKS = SCANCODE_MASK | Scancode.AC_BOOKMARKS.value
    SOFTLEFT = SCANCODE_MASK | Scancode.SOFTLEFT.value
    SOFTRIGHT = SCANCODE_MASK | Scancode.SOFTRIGHT.value
    CALL = SCANCODE_MASK | Scancode.CALL.value
    ENDCALL = SCANCODE_MASK | Scancode.ENDCALL.value
    LEFT_TAB = EXTENDED_MASK | 0x01
    LEVEL5_SHIFT = EXTENDED_MASK | 0x02
    MULTI_KEY_COMPOSE = EXTENDED_MASK | 0x03
    LMETA = EXTENDED_MASK | 0x04
    RMETA = EXTENDED_MASK | 0x05
    LHYPER = EXTENDED_MASK | 0x06
    RHYPER = EXTENDED_MASK | 0x07
