// !!! THIS FILE IS AUTO-GENERATED BY SwiftAdapter.php, DO NOT EDIT !!!
// Generated from: structs.json

import Foundation

public enum Events: UInt32 {
    case spriteAdd = 0
    case spriteRemove = 1
    case spriteMove = 2
    case spriteScale = 3
    case spriteResize = 4
    case spriteRotate = 5
    case spriteColor = 6
    case spriteSpeed = 7
    case spriteTextureLoad = 8
    case spriteTextureSet = 9
    case spriteSetSourceRect = 10
    case geomAddPoint = 50
    case geomAddLine = 51
    case geomAddRect = 52
    case geomAddFillRect = 53
    case geomAddPacked = 54
    case geomRemove = 55
    case geomSetColor = 56

    case inputKeyup = 100
    case inputKeydown = 101
    case inputMouseup = 102
    case inputMousedown = 103
    case inputMousemotion = 104

    case windowTitle = 200
    case windowResize = 201
    case windowFlags = 202

    case textAdd = 300
    case textSetString = 301

    case audioLoad = 400
    case audioLoaded = 401
    case audioPlay = 402
    case audioStopAll = 403
    case audioSetMasterVolume = 404
    case audioPause = 405
    case audioStop = 406
    case audioUnload = 407
    case audioSetVolume = 408

    case physicsAddBody = 500
    case physicsRemoveBody = 501
    case physicsApplyForce = 502
    case physicsApplyImpulse = 503
    case physicsSetVelocity = 504
    case physicsSetPosition = 505
    case physicsSetRotation = 506
    case physicsCollisionBegin = 550
    case physicsCollisionSeparate = 551
    case physicsSyncTransform = 552
    case physicsSetDebugMode = 553

    case plugin = 1000
    case pluginLoad = 1001
    case pluginUnload = 1002
    case pluginSet = 1003
    case pluginEventStacking = 1004
    case pluginSubscribeEvent = 1005
    case pluginUnsubscribeEvent = 1006

    case cameraSetPosition = 2000
    case cameraMove = 2001
    case cameraSetZoom = 2002
    case cameraSetRotation = 2003
    case cameraFollowEntity = 2004
    case cameraStopFollowing = 2005

    case scriptSubscribe = 3000
    case scriptUnsubscribe = 3001

    // --- UI (ImGui) ---
    case uiBeginWindow = 4000
    case uiEndWindow = 4001
    case uiText = 4002
    case uiButton = 4003

    // --- UI Feedback (Swift -> PHP) ---
    case uiElementClicked = 4500
}
