// !!! THIS FILE IS AUTO-GENERATED BY SwiftAdapter.php, DO NOT EDIT !!!
// Generated from: structs.json

import Foundation

// --- Platform-Specific Imports (Required for plugin loading in PhrostEngine+Plugin.swift) ---
#if os(Windows)
    import WinSDK
#elseif os(Linux)
    import Glibc
#else
    import Darwin
#endif
// --- End Platform-Specific Imports ---

@frozen public struct PackedAudioLoadEvent: Sendable {
    public var pathLength: UInt32
}

@frozen public struct PackedAudioLoadedEvent: Sendable {
    public var audioId: UInt64
}

@frozen public struct PackedAudioPauseEvent: Sendable {
    public var audioId: UInt64
}

@frozen public struct PackedAudioPlayEvent: Sendable {
    public var audioId: UInt64
}

@frozen public struct PackedAudioSetMasterVolumeEvent: Sendable {
    public var volume: Float
}

@frozen public struct PackedAudioSetVolumeEvent: Sendable {
    public var audioId: UInt64
    public var volume: Float
    public var _padding: UInt32
}

@frozen public struct PackedAudioStopAllEvent: Sendable {
    public var _unused: UInt8
}

@frozen public struct PackedAudioStopEvent: Sendable {
    public var audioId: UInt64
}

@frozen public struct PackedAudioUnloadEvent: Sendable {
    public var audioId: UInt64
}

@frozen public struct PackedCameraFollowEntityEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
}

@frozen public struct PackedCameraMoveEvent: Sendable {
    public var deltaX: Double
    public var deltaY: Double
}

@frozen public struct PackedCameraSetPositionEvent: Sendable {
    public var positionX: Double
    public var positionY: Double
}

@frozen public struct PackedCameraSetRotationEvent: Sendable {
    public var angleInRadians: Double
}

@frozen public struct PackedCameraSetZoomEvent: Sendable {
    public var zoom: Double
}

@frozen public struct PackedCameraStopFollowingEvent: Sendable {
    public var _unused: UInt8
}

@frozen public struct PackedGeomAddLineEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var z: Double
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var isScreenSpace: UInt8
    public var _padding: (UInt8, UInt8, UInt8)
    public var x1: Float
    public var y1: Float
    public var x2: Float
    public var y2: Float
}

@frozen public struct PackedGeomAddPackedHeaderEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var z: Double
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var isScreenSpace: UInt8
    public var _padding: UInt16
    public var primitiveType: UInt32
    public var count: UInt32
}

@frozen public struct PackedGeomAddPointEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var z: Double
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var isScreenSpace: UInt8
    public var _padding: (UInt8, UInt8, UInt8)
    public var x: Float
    public var y: Float
}

@frozen public struct PackedGeomAddPolygonHeaderEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var z: Double
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var isScreenSpace: UInt8
    public var _padding: (UInt8, UInt8, UInt8)
    public var vertexCount: UInt32
}

@frozen public struct PackedGeomAddRectEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var z: Double
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var isScreenSpace: UInt8
    public var _padding: (UInt8, UInt8, UInt8)
    public var x: Float
    public var y: Float
    public var w: Float
    public var h: Float
}

@frozen public struct PackedGeomRemoveEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
}

@frozen public struct PackedGeomSetColorEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var _padding: UInt32
}

@frozen public struct PackedKeyEvent {
    public var scancode: Int32
    public var keycode: UInt32
    public var mod: UInt16
    public var isRepeat: UInt8
    public var _padding: UInt8
}

@frozen public struct PackedMouseButtonEvent {
    public var x: Float
    public var y: Float
    public var button: UInt8
    public var clicks: UInt8
    public var _padding: UInt16
}

@frozen public struct PackedMouseMotionEvent {
    public var x: Float
    public var y: Float
    public var xrel: Float
    public var yrel: Float
}

@frozen public struct PackedPhysicsAddBodyEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var positionX: Double
    public var positionY: Double
    public var bodyType: UInt8
    public var shapeType: UInt8
    public var lockRotation: UInt8
    public var _padding: (UInt8, UInt8, UInt8, UInt8, UInt8)
    public var mass: Double
    public var friction: Double
    public var elasticity: Double
    public var width: Double
    public var height: Double
}

@frozen public struct PackedPhysicsApplyForceEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var forceX: Double
    public var forceY: Double
}

@frozen public struct PackedPhysicsApplyImpulseEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var impulseX: Double
    public var impulseY: Double
}

@frozen public struct PackedPhysicsCollisionEvent: Sendable {
    public var id1_A: Int64
    public var id2_A: Int64
    public var id1_B: Int64
    public var id2_B: Int64
}

@frozen public struct PackedPhysicsRemoveBodyEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
}

@frozen public struct PackedPhysicsSetDebugModeEvent: Sendable {
    public var enabled: UInt8
    public var _padding: (UInt8, UInt8, UInt8)
}

@frozen public struct PackedPhysicsSetPositionEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var positionX: Double
    public var positionY: Double
}

@frozen public struct PackedPhysicsSetRotationEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var angleInRadians: Double
}

@frozen public struct PackedPhysicsSetVelocityEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var velocityX: Double
    public var velocityY: Double
}

@frozen public struct PackedPhysicsSyncTransformEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var positionX: Double
    public var positionY: Double
    public var angle: Double
    public var velocityX: Double
    public var velocityY: Double
    public var angularVelocity: Double
    public var isSleeping: UInt8
    public var _padding: (UInt8, UInt8, UInt8, UInt8, UInt8, UInt8, UInt8)
}

@frozen public struct PackedPluginEventStackingEvent: Sendable {
    public var eventId: UInt8
    public var _padding: UInt8
}

@frozen public struct PackedPluginLoadHeaderEvent: Sendable {
    public var channelNo: UInt32
    public var pathLength: UInt32
}

@frozen public struct PackedPluginOnEvent: Sendable {
    public var eventId: UInt8
}

@frozen public struct PackedPluginSetEvent: Sendable {
    public var pluginId: UInt8
}

@frozen public struct PackedPluginSubscribeEvent: Sendable {
    public var pluginId: UInt8
    public var _padding: (UInt8, UInt8, UInt8)
    public var channelNo: UInt32
}

@frozen public struct PackedPluginUnloadEvent: Sendable {
    public var pluginId: UInt8
}

@frozen public struct PackedPluginUnsubscribeEvent: Sendable {
    public var pluginId: UInt8
    public var _padding: (UInt8, UInt8, UInt8)
    public var channelNo: UInt32
}

@frozen public struct PackedScriptSubscribeEvent: Sendable {
    public var channelNo: UInt32
    public var _padding: UInt32
}

@frozen public struct PackedScriptUnsubscribeEvent: Sendable {
    public var channelNo: UInt32
    public var _padding: UInt32
}

@frozen public struct PackedSpriteAddEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var positionX: Double
    public var positionY: Double
    public var positionZ: Double
    public var scaleX: Double
    public var scaleY: Double
    public var scaleZ: Double
    public var sizeW: Double
    public var sizeH: Double
    public var rotationX: Double
    public var rotationY: Double
    public var rotationZ: Double
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var _padding: UInt32
    public var speedX: Double
    public var speedY: Double
}

@frozen public struct PackedSpriteColorEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var _padding: UInt32
}

@frozen public struct PackedSpriteMoveEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var positionX: Double
    public var positionY: Double
    public var positionZ: Double
}

@frozen public struct PackedSpriteRemoveEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
}

@frozen public struct PackedSpriteResizeEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var sizeW: Double
    public var sizeH: Double
}

@frozen public struct PackedSpriteRotateEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var rotationX: Double
    public var rotationY: Double
    public var rotationZ: Double
}

@frozen public struct PackedSpriteScaleEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var scaleX: Double
    public var scaleY: Double
    public var scaleZ: Double
}

@frozen public struct PackedSpriteSetSourceRectEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var x: Float
    public var y: Float
    public var w: Float
    public var h: Float
}

@frozen public struct PackedSpriteSpeedEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var speedX: Double
    public var speedY: Double
}

@frozen public struct PackedSpriteTextureSetEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var textureId: UInt64
}

@frozen public struct PackedTextAddEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var positionX: Double
    public var positionY: Double
    public var positionZ: Double
    public var r: UInt8
    public var g: UInt8
    public var b: UInt8
    public var a: UInt8
    public var _padding1: UInt32
    public var fontSize: Float
    public var fontPathLength: UInt32
    public var textLength: UInt32
    public var _padding2: UInt32
}

@frozen public struct PackedTextSetStringEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var textLength: UInt32
    public var _padding: UInt32
}

@frozen public struct PackedTextureLoadHeaderEvent: Sendable {
    public var id1: Int64
    public var id2: Int64
    public var filenameLength: UInt32
    public var _padding: UInt32
}

@frozen public struct PackedUIBeginWindowHeaderEvent: Sendable {
    public var id: UInt32
    public var flags: UInt32
    public var titleLength: UInt32
    public var _padding: UInt32
}

@frozen public struct PackedUIButtonHeaderEvent: Sendable {
    public var id: UInt32
    public var w: Float
    public var h: Float
    public var labelLength: UInt32
}

@frozen public struct PackedUIEndWindowEvent: Sendable {
    public var _unused: UInt8
}

@frozen public struct PackedUIInteractionEvent: Sendable {
    public var elementId: UInt32
    public var interactionType: UInt32
}

@frozen public struct PackedUISetNextWindowPosEvent: Sendable {
    public var x: Float
    public var y: Float
    public var cond: UInt32
    public var pivotX: Float
    public var pivotY: Float
}

@frozen public struct PackedUISetNextWindowSizeEvent: Sendable {
    public var w: Float
    public var h: Float
    public var cond: UInt32
}

@frozen public struct PackedUITextHeaderEvent: Sendable {
    public var textLength: UInt32
    public var _padding: UInt32
}

@frozen public struct PackedUIWindowClosedEvent: Sendable {
    public var windowId: UInt32
}

@frozen public struct PackedWindowFlagsEvent {
    public var flags: UInt64
}

@frozen public struct PackedWindowResizeEvent {
    public var w: Int32
    public var h: Int32
}

@frozen public struct PackedWindowTitleEvent {
    public var title:
        (
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar,
            CChar, CChar, CChar, CChar, CChar, CChar, CChar, CChar
        )

    public init(title newTitle: String) {
        self.title = (
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
            0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
        )

        withUnsafeMutableBytes(of: &self.title) { buffer in
            newTitle.withCString { cString in
                guard let dest = buffer.baseAddress?.assumingMemoryBound(to: CChar.self) else {
                    return
                }

                #if os(Windows)
                    strcpy_s(dest, buffer.count, cString)
                #else
                    strlcpy(dest, cString, buffer.count)
                #endif
            }
        }
    }
}
